#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Products.Resource", IsApplication=true)]

namespace Products
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box_trot = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int loginBtn = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int loginInputPassword = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int loginInputUsername = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int productsFragment = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int productsList = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int productsListCellPrice = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int productsListCellTitle = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Products = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ProductsListCell = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ProductsListFragment = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int login_btn = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int login_intro = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int login_message_denied = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int login_message_success = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int login_password = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int login_title = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int login_username = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
