#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Products.Resource", IsApplication=true)]

namespace Products
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Products.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Products.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Products.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int enter_from_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int exit_to_left = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box_trot = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000f
			public const int contentFrame = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int loginBtn = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int loginInputPassword = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int loginInputUsername = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int productDetailDescription = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int productDetailLink = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int productDetailPrice = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int productDetailTitle = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int productsDetailFragment = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int productsFragment = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int productsFragmentContainer = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int productsList = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int productsListCellPrice = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int productsListCellTitle = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int productsListScanBtn = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int productsListTimestamp = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Products = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ProductsDetailFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ProductsListCell = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ProductsListFragment = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int zxingscanneractivitylayout = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int zxingscannerfragmentlayout = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int login_btn = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int login_intro = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int login_message_denied = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int login_message_success = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int login_password = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int login_title = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int login_username = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int price = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int product_detail_not_selected = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
